class CS {
  static String AppNmae = "PK Games";
  static String winningamount = "winningamount";
  static final String serviceName = "serviceName";
  static final String clientpayment = "clientpayment";
  static final String main_title = "main_title";
  static final String student_id = "student_id";
  static final String sub_institute_id = "sub_institute_id";
  static final String lstclientpaymentlistdata = "lstclientpaymentlistdata";
  static final String TransactionNumber = "TransactionNumber";
  static final String resultdate = "resultdate";
  static final String isdeleteview = "isdeleteview";
  static final String number2 = "number2";
  static final String datetime = "datetime";
  static final String purchasedatetime = "purchasedatetime";
  static final String ticketid = "ticketid";
  static final String openclose = "openclose";
  static final String purchaseid = "purchaseid";
  static final String lstpurchaselistdata = "lstpurchaselistdata";
  static final String openclosename = "openclosename";
  static final String number = "number";
  static final String BankAccountName = "BankAccountName";
  static final String MobileNo = "MobileNo";
  static final String Amount = "Amount";
  static final String ApproveStatus = "ApproveStatus";
  static final String result = "result";
  static final String lstpurchaseitemlistdata = "lstpurchaseitemlistdata";
  static final String TransactionMobileNo = "TransactionMobileNo";
  static final String lastgameresult = "lastgameresult";
  static final String WithdrawMode = "WithdrawMode";
  static final String token = "token";
  static final String GameType = "GameType";
  static final String GameRate = "GameRate";
  static final String lstclientwithdrawlistdata = "lstclientwithdrawlistdata";
  static final String lms_user_id = "lms_user_id";
  static final String org_ans = "org_ans";
  static final String userid = "userid";
  static final String type = "type";
  static final String purchasedata = "purchasedata";
  static final String user_id = "user_id";
  static final String clientwithdraw = "clientwithdraw";
  static final String gameid = "gameid";
  static final String lstgamedata = "lstgamedata";
  static final String menu_type = "menu_type";
  static final String amount = "amount";
  static final String gamename = "gamename";
  static final String opentime = "opentime";
  static final String closetime = "closetime";
  static final String grade = "grade";
  static final String main_title_background_image = "main_title_background_image";
  static final String sub_title_icon = "sub_title_icon";
  static final String main_itle_color = "main_itle_color";
  static final String sub_title = "sub_title";
  static final String orignal_ans = "orignal_ans";
  static final String total = "total";
  static final String screen_name = "screen_name";
  static final String question_layout = "question_layout";
  static final String given_ans = "given_ans";
  static final String chapter_id = "chapter_id";
  static final String chapter_name = "chapter_name";
  static final String isRegisterd = "isRegisterd";
  static final String deviceType = "deviceType";
  static final String deviceId = "deviceId";
  static final String deviceVersion = "deviceVersion";
  static final String latitude = "latitude";
  static final String longitude = "longitude";
  static final String questiontext = "questiontext";
  static final String quetionname = "quetionname";
  static final String image_path = "image_path";
  static final String questionid = "questionid";
  static final String defaultmark = "defaultmark";
  static final String qtype = "qtype";
  static final String option = "option";
  static final String answerid = "answerid";
  static final String answertext = "answertext";
  static final String correct = "correct";
  static final String modify_date = "modify_date";
  static final String exam_time = "exam_time";
  static final String cnt = "cnt";
  static final String deviceName = "deviceName";
  static final String chaptername = "chaptername";
  static final String modicon = "modicon";
  static final String chapterid = "chapterid";
  static final String mimetype = "mimetype";
  static final String id = "id";
  static final String name = "name";
  static final String fileurl = "fileurl";
  static final String contents = "contents";
  static final String roll_no = "roll_no";
  static final String first_name = "first_name";
  static final String last_name = "last_name";
  static final String section = "section";
  static final String std_name = "std_name";
  static final String birthday = "birthday";
  static final String address = "address";
  static final String gender = "gender";
  static final String father_name = "father_name";
  static final String mother_name = "mother_name";
  static final String U_ID = "U_ID";
  static final String division = "division";
  static final String appVersion = "appVersion";
  static final String courseid = "courseid";
  static final String course_id = "course_id";
  static final String chapters = "chapters";
  static final String isComplusory = "isComplusory";
  static final String idnumber = "idnumber";
  static final String displayname = "displayname";
  static final String isUpdate = "isUpdate";
  static final String updateVersionText = "updateVersionText";
  static final String mobile = "mobile";
  static final String password = "password";
  static final String maintenance_message = "maintenance_message";
  static final String is_maintenance = "is_maintenance";
  static final String ios = "ios";
  static final String android = "android";
  static final String status = "status";
  static final String message = "message";
  static final String userName = "userName";
  static final String userPassword = "userPassword";
  static final String deviceToken = "deviceToken";
  static final String otp = "otp";
  static final String clientdata = "clientdata";
  static final String lstclientdata = "lstclientdata";
  static final String otp_generate = "otp_generate";
  static final String value = "value";
  static final String homeDetails = "homeDetails";
  static final String categoryId = "categoryId";
  static final String lsteopenclosedata = "lsteopenclosedata";
  static final String title = "title";
  static final String Number = "Number";
  static final String Value = "Value";
  static final String menuList = "menuList";
  static final String image = "image";
  static final String menuID = "menuID";
  static final String menuName = "menuName";
  static final String indexOrder = "indexOrder";
  static final String url = "url";
  static final String isRedirect = "isRedirect";
  static final String redirectScreen = "redirectScreen";
  static final String isBrowser = "isBrowser";
  static final String modules = "modules";
  static final String data = "data";
  static final String isBtnShow = "isBtnShow";
  static final String aspectRatio = "aspectRatio";
  static final String key = "key";
  static final String pageNo = "pageNo";
  static final String limit = "limit";
  static final String feedBack = "feedBack";
  static final String notification = "notification";
  static final String StudentPhoto = "StudentPhoto";
  static final String body = "body";
  static final String Video = "Video";
  static final String Ppt = "Ppt";
  static final String Pdf = "Pdf";
  static final String fromDate = "fromDate";
  static final String toDate = "toDate";
  static final String notes = "notes";
  static final String RETRY = "RETRY";
  static final String Update = "UPDATE";
  static final String file = "file";
  static final String currPassword = "currPassword";
  static final String newPassword = "newPassword";
  static final String isRead = "isRead";
  static final String time = "time";
  static final String link = "link";
  static final String cancel = "CANCEL";
  static final String day = "day";
  static final String startDay = "startDay";
  static final String endDay = "endDay";
  static final String play_screen = "play_screen";
  static final String aps = "aps";
  static final String alert = "alert";
  static const String MyCourse = "My Course";
  static const String MyAssessment = "My Assessment";
  static const String MyResult = "My Result";
  static final String subMenuList = "subMenuList";
  static final String lstgameresultlistdata = "lstgameresultlistdata";

  //Service
  static final String termsconditionLink = "https://pkgames.online/terms";
  static final String login = "https://pkgames.online/API/APIMatka.aspx?api=2&organizationid=1&otp=1";
  static final String profileSave = "https://pkgames.online/API/APIMatka.aspx?api=2&organizationid=1&otp=2";
  static final String lstpurchaselist = "https://pkgames.online/API/APIMatka.aspx?api=12&clientid=";
  static final String lstgameresultlist = "https://pkgames.online/API/APIMatka.aspx?api=15&gameId=";
  static final String lstpurchasedelete = "https://pkgames.online/API/APIMatka.aspx?api=14&PurchaseId=";
  static final String lstpurchaseitemlist = "https://pkgames.online/API/APIMatka.aspx?api=13&PurchaseId=";
  static final String clientPaymentSave = "https://pkgames.online/API/APIMatka.aspx?api=6";
  static final String purchaseDataSave = "https://pkgames.online/API/APIMatka.aspx?api=3&organizationid=1";
  static final String clientWithdrawSave = "https://pkgames.online/API/APIMatka.aspx?api=7";
  static final String lstclientwithdraw = "https://pkgames.online/APIMatka.aspx?api=11&clientid=";
  static final String lstbalancelist = "https://pkgames.online/API/APIMatka.aspx?api=10&clientid=";
  static final String walletAmount = "https://pkgames.online/APIMatka.aspx?api=9&clientid=";
  static final String organizationDataSave = "https://pkgames.online/API/APIMatka.aspx?api=8&organizationid=1";
  static final String homeScreen = "https://pkgames.online/API/APIMatka.aspx?api=1&organizationid=1&MobileNo=";
  static final String DetailDropDownScreen = "https://pkgames.online/API/APIMatka.aspx?api=16&organizationid=1";

/*
  static final String termsconditionLink = "http://student.Matka Master.com/terms";
  static final String login = "http://matka.flomiz.com/API/APIMatka.aspx?api=2&organizationid=1&otp=1";
  static final String profileSave = "http://matka.flomiz.com/API/APIMatka.aspx?api=2&organizationid=1&otp=2";
  static final String lstpurchaselist = "http://matka.flomiz.com/API/APIMatka.aspx?api=12&clientid=";
  static final String lstgameresultlist = "http://matka.flomiz.com/API/APIMatka.aspx?api=15&gameId=";
  static final String lstpurchasedelete = "http://matka.flomiz.com/API/APIMatka.aspx?api=14&PurchaseId=";
  static final String lstpurchaseitemlist = "http://matka.flomiz.com/API/APIMatka.aspx?api=13&PurchaseId=";
  static final String clientPaymentSave = "http://matka.flomiz.com/API/APIMatka.aspx?api=6";
  static final String purchaseDataSave = "http://matka.flomiz.com/API/APIMatka.aspx?api=3&organizationid=1";
  static final String clientWithdrawSave = "http://matka.flomiz.com/API/APIMatka.aspx?api=7";
  static final String lstclientwithdraw = "http://matka.flomiz.com/API/APIMatka.aspx?api=11&clientid=";
  static final String lstbalancelist = "http://matka.flomiz.com/API/APIMatka.aspx?api=10&clientid=";
  static final String walletAmount = "http://matka.flomiz.com/API/APIMatka.aspx?api=9&clientid=";
  static final String organizationDataSave = "http://matka.flomiz.com/API/APIMatka.aspx?api=8&organizationid=1";
  static final String homeScreen = "http://matka.flomiz.com/API/APIMatka.aspx?api=1&organizationid=1";
  static final String DetailDropDownScreen = "http://matka.flomiz.com/API/APIMatka.aspx?api=16&organizationid=1";
*/

  //Message String
//  We can not detect any internet connectivity.Please
  static final String NoInernetError = "Check your internet connection and try again";
  static final String InternalServerError = "Internal Server Error";
  static final String NoPaper = "No Paper Data found.";
  static final String ConnectionErrror = "Connection Timeout";
  static const String UPLOAD_PAPER = "UPLOAD PAPER";
  static const String READING_LIST = "READING LIST";
  static const String Profile = "Profile";
  static const String ComingSoon = "Coming Soon...";
}

const String strMenu =
    '[{"menuID": "9","menuName": "Home","indexOrder": "1","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon2/Home.png","url": "0","isRedirect": "1","redirectScreen": "1","isBrowser": "0","subMenuList": []},{"menuID": "1","menuName": "Profile","indexOrder": "2","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon/Profile.png","url": "0","isRedirect": "1","redirectScreen": "ProfileScreen","isBrowser": "0","subMenuList": [{"menuID": "301","menuName": "My Profile","indexOrder": "2","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon2/My Profile.png","url": "0","isRedirect": "1","redirectScreen": "ProfileScreen","isBrowser": "0"},{"menuID": "303","menuName": "Change Password","indexOrder": "2","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon2/Change%20Pass.png","url": "0","isRedirect": "1","redirectScreen": "12","isBrowser": "0"}]},{"menuID": "3","menuName": "Settings","indexOrder": "5","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon/Setting.png","url": "0","isRedirect": "1","redirectScreen": "12","isBrowser": "0","subMenuList": []},{"menuID": "4","menuName": "About US","indexOrder": "7","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon/Aboutus.png","url": "0","isRedirect": "1","redirectScreen": "","isBrowser": "0","subMenuList": []},{"menuID": "2","menuName": "Contact US","indexOrder": "8","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon/Contact us.png","url": "0","isRedirect": "1","redirectScreen": "","isBrowser": "0","subMenuList": []},{"menuID": "6","menuName": "Rate","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon/Rate.png","url": "http://student.intstu.com/terms","isRedirect": "1","redirectScreen": "","isBrowser": "0","subMenuList": []},{"menuID": "7","menuName": "Share","menuNameGujarati": "ગોપનીયતા નીતિ","indexOrder": "13","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon/Share.png","url": "http://student.intstu.com/privacy","isRedirect": "1","redirectScreen": "","isBrowser": "0","subMenuList": []},{"menuID": "8","menuName": "Logout","menuNameGujarati": "લૉગ આઉટ","indexOrder": "15","image": "http://uat.ocxee.com/ocxee-app-images-iphone/icon/Logout.png","url": "0","isRedirect": "1","redirectScreen": "100","isBrowser": "0","subMenuList": []}]';

const String strSP =
    '[{ "Number":"128"},{ "Number":"137"},{ "Number":"146"},{ "Number":"236"},{ "Number":"245"},{ "Number":"290"},{ "Number":"380"},{ "Number":"470"},{ "Number":"489"},{ "Number":"560"},{ "Number":"579"},{ "Number":"678"},{ "Number":"129"},{ "Number":"138"},{ "Number":"147"},{ "Number":"156"},{ "Number":"237"},{ "Number":"246"},{ "Number":"345"},{ "Number":"390"},{ "Number":"480"},{ "Number":"570"},{ "Number":"589"},{ "Number":"679"},{ "Number":"120"},{ "Number":"139"},{ "Number":"148"},{ "Number":"157"},{ "Number":"238"},{ "Number":"247"},{ "Number":"256"},{ "Number":"346"},{ "Number":"490"},{ "Number":"580"},{ "Number":"670"},{ "Number":"689"},{ "Number":"130"},{ "Number":"149"},{ "Number":"158"},{ "Number":"167"},{ "Number":"239"},{ "Number":"248"},{ "Number":"257"},{ "Number":"347"},{ "Number":"356"},{ "Number":"590"},{ "Number":"680"},{ "Number":"789"},{ "Number":"140"},{ "Number":"159"},{ "Number":"168"},{ "Number":"230"},{ "Number":"249"},{ "Number":"258"},{ "Number":"268"},{ "Number":"348"},{ "Number":"357"},{ "Number":"456"},{ "Number":"690"},{ "Number":"780"},{ "Number":"123"},{ "Number":"150"},{ "Number":"169"},{ "Number":"178"},{ "Number":"240"},{ "Number":"259"},{ "Number":"268"},{ "Number":"349"},{ "Number":"358"},{ "Number":"367"},{ "Number":"457"},{ "Number":"790"},{ "Number":"124"},{ "Number":"160"},{ "Number":"179"},{ "Number":"250"},{ "Number":"269"},{ "Number":"278"},{ "Number":"340"},{ "Number":"359"},{ "Number":"368"},{ "Number":"458"},{ "Number":"467"},{ "Number":"890"},{ "Number":"125"},{ "Number":"134"},{ "Number":"170"},{ "Number":"189"},{ "Number":"260"},{ "Number":"279"},{ "Number":"350"},{ "Number":"369"},{ "Number":"378"},{ "Number":"459"},{ "Number":"468"},{ "Number":"567"},{ "Number":"126"},{ "Number":"135"},{ "Number":"180"},{ "Number":"234"},{ "Number":"270"},{ "Number":"289"},{ "Number":"360"},{ "Number":"379"},{ "Number":"450"},{ "Number":"469"},{ "Number":"478"},{ "Number":"568"},{ "Number":"127"},{ "Number":"136"},{ "Number":"145"},{ "Number":"190"},{ "Number":"235"},{ "Number":"280"},{ "Number":"370"},{ "Number":"389"},{ "Number":"460"},{ "Number":"479"},{ "Number":"569"},{ "Number":"578"}]';

const String strDP =
    '[{ "Number":"100"},{ "Number":"119"},{ "Number":"155"},{ "Number":"227"},{ "Number":"335"},{ "Number":"344"},{ "Number":"399"},{ "Number":"588"},{ "Number":"669"},{ "Number":"110"},{ "Number":"200"},{ "Number":"228"},{ "Number":"255"},{ "Number":"336"},{ "Number":"499"},{ "Number":"660"},{ "Number":"688"},{ "Number":"778"},{ "Number":"166"},{ "Number":"229"},{ "Number":"300"},{ "Number":"337"},{ "Number":"355"},{ "Number":"445"},{ "Number":"599"},{ "Number":"779"},{ "Number":"788"},{ "Number":"112"},{ "Number":"220"},{ "Number":"266"},{ "Number":"338"},{ "Number":"400"},{ "Number":"446"},{ "Number":"455"},{ "Number":"699"},{ "Number":"770"},{ "Number":"113"},{ "Number":"122"},{ "Number":"177"},{ "Number":"339"},{ "Number":"366"},{ "Number":"447"},{ "Number":"500"},{ "Number":"799"},{ "Number":"889"},{ "Number":"114"},{ "Number":"277"},{ "Number":"330"},{ "Number":"448"},{ "Number":"466"},{ "Number":"556"},{ "Number":"600"},{ "Number":"880"},{ "Number":"899"},{ "Number":"115"},{ "Number":"133"},{ "Number":"188"},{ "Number":"223"},{ "Number":"377"},{ "Number":"449"},{ "Number":"557"},{ "Number":"566"},{ "Number":"700"},{ "Number":"116"},{ "Number":"224"},{ "Number":"233"},{ "Number":"288"},{ "Number":"440"},{ "Number":"477"},{ "Number":"558"},{ "Number":"800"},{ "Number":"990"},{ "Number":"117"},{ "Number":"144"},{ "Number":"199"},{ "Number":"225"},{ "Number":"388"},{ "Number":"559"},{ "Number":"577"},{ "Number":"667"},{ "Number":"900"},{ "Number":"118"},{ "Number":"226"},{ "Number":"244"},{ "Number":"299"},{ "Number":"334"},{ "Number":"488"},{ "Number":"550"},{ "Number":"668"},{ "Number":"677"}]';

const String strTPana = '[{ "Number":"777"},{ "Number":"444"},{ "Number":"111"},{ "Number":"888"},{ "Number":"555"},{ "Number":"222"},{ "Number":"999"},{ "Number":"666"},{ "Number":"333"},{ "Number":"000"}]';

const String strGameRate =
    '[{   "GameType":"SINGLE ANK * 10",   "GameRate":"95"  },{   "GameType":"JODI[BRACKET] * 10",   "GameRate":"950"},{   "GameType":"SINGLE PATTI * 10",   "GameRate":"1400"  },{   "GameType":"DOUBLE PATTI * 10",   "GameRate":"2800" },{   "GameType":"HALF SANGAM * 10",   "GameRate":"10000"  },{   "GameType":"FULL SANGAM * 10",   "GameRate":"100000"  }]';

const String k_clientid = "clientid";
const String k_lstorganizationdata = "lstorganizationdata";
const String k_contactno = "contactno";
const String k_Walletamount = "Walletamount";
const String k_walletamount = "walletamount";
